=== inspectr-hq/inspectr/schema/inspectr-request.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Inspectr HTTP Request/Response",
  "type": "object",
  "properties": {
    "method": {
      "type": "string"
    },
    "url": {
      "type": "string",
      "format": "uri"
    },
    "server": {
      "type": "string"
    },
    "path": {
      "type": "string"
    },
    "clientIp": {
      "type": "string"
    },
    "latency": {
      "type": "number"
    },
    "request": {
      "type": "object",
      "properties": {
        "payload": {
          "type": "string"
        },
        "headers": {
          "type": "object"
        },
        "queryParams": {
          "type": "object"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "payload",
        "headers",
        "queryParams",
        "timestamp"
      ]
    },
    "response": {
      "type": "object",
      "properties": {
        "payload": {
          "type": "string"
        },
        "headers": {
          "type": "object"
        },
        "statusCode": {
          "type": "integer"
        },
        "statusMessage": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "payload",
        "headers",
        "statusCode",
        "statusMessage",
        "timestamp"
      ]
    }
  },
  "required": [
    "method",
    "url",
    "server",
    "path",
    "clientIp",
    "latency",
    "request",
    "response"
  ]
}

=== inspectr-hq/inspectr/schema/inspectr-request.example.json
{
  "method": "POST",
  "url": "http://localhost:3000/api/users?sort=asc",
  "server": "localhost:3000",
  "path": "/api/users",
  "clientIp": "192.168.1.100",
  "latency": 120,
  "request": {
    "payload": "{\"name\":\"Marco Polo\",\"email\":\"marco@polo-ventures.com\"}",
    "headers": {
      "Content-Type": "application/json",
      "Host": "localhost:3000"
    },
    "queryParams": {
      "sort": "asc"
    },
    "timestamp": "2025-02-14T15:00:00.000Z"
  },
  "response": {
    "payload": "{\"success\":true,\"id\":123}",
    "headers": {
      "Content-Type": "application/json"
    },
    "statusCode": 200,
    "statusMessage": "OK",
    "timestamp": "2025-02-14T15:00:00.120Z"
  }
}
